export function getCodexHandoffProtocol() {
  return {
    schemaVersion: 1,
    kind: "codex_handoff_protocol",
    generatedAt: new Date().toISOString(),
    mutates: false,
    title: "Codex Handoff Protocol",
    summary: "Codex remains the builder. Hermes becomes the reviewer/operator.",
    document: "docs/CODEX_HANDOFF_PROTOCOL.md",
    roles: {
      builder: "Codex edits code, works in branches/worktrees, opens PRs, and fixes failures.",
      reviewerOperator: "Hermes reviews PR risk, runs read-only checks, reports to PR comments/Slack/monitor, and proposes actions without broad merge/deploy execution.",
      approver: "Human owner approves merge, deploy, override, rollback, or secret rotation.",
    },
    flow: [
      "Codex opens or updates a PR.",
      "GitHub CI runs.",
      "GitHub Actions calls averray_invoke_agent_task with intent=pr_code_review.",
      "GitHub Actions calls averray_invoke_agent_task with intent=pr_handoff and requested read-only testbed cases.",
      "Hermes records handoff events and, when enabled, upserts one PR verdict comment alongside Slack and monitor reports.",
      "Codex responds to PASS / HUMAN REVIEW / BLOCK.",
      "After merge/deploy, Hermes runs post_deploy_verification.",
    ],
    codexPrRequirements: [
      "What changed.",
      "Checks run locally.",
      "Affected surfaces: backend, frontend, indexer, Caddy, contracts, public site, workflows, docs, tests, or secrets/config.",
      "Rollout or rollback notes for deploy, workflow, ops, contract, indexer, database, or secret-sensitive changes.",
      "Known limits, skipped checks, or follow-up work.",
    ],
    hermesChecks: [
      "PR state, draft flag, author, branch, mergeability, and update time.",
      "Changed files, touched surfaces, and high-risk file categories.",
      "Failed, active, missing, skipped, neutral, and passed CI checks.",
      "Test signal coverage for touched areas.",
      "Rollout/rollback note presence for deploy-sensitive changes.",
      "Requested read-only testbed cases such as TBE2E-004.",
    ],
    verdicts: [
      {
        label: "PASS",
        meaning: "No blocking or review-gated release signal was found.",
        codexAction: "Continue normal merge queue or ask the human owner for final approval.",
      },
      {
        label: "HUMAN REVIEW",
        meaning: "Not necessarily broken; review-gated surface or incomplete automated proof needs a human look.",
        codexAction: "Explain the risk, tests, and rollout/rollback plan in the PR, then ask the human owner to review.",
      },
      {
        label: "BLOCK",
        meaning: "Do not merge or deploy until fixed or explicitly overridden by a human owner outside Hermes.",
        codexAction: "Stop, fix the PR or missing evidence, wait for CI, and let Hermes re-run.",
      },
    ],
    metadata: {
      requester: "github-actions | codex | backend-agent",
      repo: "owner/repo",
      pullRequestNumber: "GitHub PR number",
      sha: "head or deployed commit SHA",
      correlationId: "github-pr-<number>-<sha>-<workflowRunId> or github-deploy-<runId>-<sha>",
      testCaseIds: "requested read-only testbed cases",
      reason: "short source phrase such as post-CI PR handoff",
    },
    contracts: {
      prCodeReview: {
        requester: "github-actions",
        intent: "pr_code_review",
        repo: "averray-agent/agent",
        pullRequestNumber: 123,
        correlationId: "github-pr-123-abc-456-code-review",
        reason: "post-CI independent PR verifier",
      },
      prHandoff: {
        requester: "github-actions",
        intent: "pr_handoff",
        repo: "averray-agent/agent",
        pullRequestNumber: 123,
        testCaseIds: ["TBE2E-004"],
        correlationId: "github-pr-123-abc-456",
        reason: "post-CI PR handoff",
      },
      postDeploy: {
        requester: "github-actions",
        intent: "post_deploy_verification",
        repo: "averray-agent/agent",
        sha: "abc1234",
        correlationId: "github-deploy-456-abc1234",
        reason: "post-production-deploy verification",
      },
    },
    safety: {
      readOnly: true,
      mutates: false,
      optionalPrCommentMutatesGithub: true,
      secretsIncluded: false,
      githubMutated: false,
      mergePerformed: false,
      deployTriggered: false,
      freeFormHermesPromptUsed: false,
      noNewIntegrationRequired: true,
      emailProviderRequired: false,
    },
  };
}
